# Generated by Django 2.0.2 on 2018-02-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180215_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='Оптимальный размер: 1200px*750px.', null=True, upload_to='about/', verbose_name='Изображение'),
        ),
    ]
