# Generated by Django 2.0.2 on 2018-02-16 08:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180215_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='form_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
