# Generated by Django 2.0.2 on 2018-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180216_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contact_type', models.PositiveSmallIntegerField(choices=[(1, 'Телефон'), (2, 'E-Mail')], verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контактные данные в "шапке" и "подвале"',
            },
        ),
    ]
