# Generated by Django 2.0.2 on 2018-02-14 12:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('meta_h1', models.CharField(max_length=255, verbose_name='Текст 1')),
                ('text_2', models.CharField(max_length=255, verbose_name='Текст 2')),
                ('text_3', ckeditor.fields.RichTextField(verbose_name='Текст 3')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
