# Generated by Django 2.0.2 on 2018-02-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Данные страницы', 'verbose_name_plural': 'Данные страницы'},
        ),
    ]
