# Generated by Django 2.0.2 on 2018-02-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ('created_at',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Галерея товара'},
        ),
    ]
