# Generated by Django 2.0.2 on 2018-02-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180219_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'permissions': (('can_see_price', 'Может смотреть цену'),), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
