# Generated by Django 2.0.2 on 2018-02-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180223_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Оптимальное разрешение - 400px * 270px', null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
    ]
