# Generated by Django 2.0.2 on 2018-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180226_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Используется при формировании ссылки на страницу товара.', max_length=255, verbose_name='Slug'),
        ),
    ]
